account_id = "2f603d82990d91696c626ad72497dd54"
name = "cloudflare-bot"
main = "src/index.ts"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-03-09"
nodejs_compat = true
BOT_INFO="""{
    "id": 8120385552,
    "is_bot": true,
    "first_name": "Mini App development for Telegram Environment",
    "username": "MiniAppDevelopmentBot",
    "can_join_groups": true,
    "can_read_all_group_messages": false,
    "supports_inline_queries": false,
    "can_connect_to_business": false
}"""

